### ISSUE TITLE
Colaboración e incorporación de miembro

### ISSUE THREAD

**Issue by cdyurquina** [ValleGalan/devtech-podcast-web#3]
Hola ValleGalan,

quisiera colaborar con tu proyecto incorporándome como miembro del equipo del podcast DevTech. Para ello agregaré mi información en la tarjeta 3 (derecha) como se acordó previamente con el equipo. Te adjunto captura del resultado:

![image](https://user-images.githubusercontent.com/79678415/178433348-b77a083e-3e97-4107-a79f-3b8e4c4245f8.png)

Saludos!

C.Y.

**Comment by ValleGalan** [comment]
Hola Cristian :D, dale .
